// skill-swap-frontend/src/pages/login/Login.tsx
import React, { useState } from 'react';
import styles from '../register/Register.module.css';
import { useNavigate } from 'react-router-dom';
import { AuthContext } from '../../context/AuthContext';

const Login = () => {
  const [formData, setFormData] = useState({
    username: '',
    password: '',
  });

  const { login } = React.useContext(AuthContext);
  const navigate = useNavigate();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prevFormData => ({
      ...prevFormData,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      const response = await fetch('http://localhost:3000/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      const result = await response.json();

      if (response.ok) {
        localStorage.setItem('token', result.access_token);
        localStorage.setItem('userId', JSON.stringify(result.user));
        
        login();
        navigate('/');
      } else {
        console.error('Greška pri prijavi:', result);
        alert(`Greška: ${result.message || 'Neuspešna prijava'}`);
      }
    } catch (error) {
      console.error('Greška pri slanju zahteva:', error);
      alert('Došlo je do greške. Pokušajte ponovo.');
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.authBox}>
        <h1 className={styles.heading}>Prijavi se</h1>
        <form className={styles.form} onSubmit={handleSubmit}>
          <input
            type="text"
            name="username"
            placeholder="Korisničko ime"
            className={styles.input}
            value={formData.username}
            onChange={handleChange}
            required
          />
          <input
            type="password"
            name="password"
            placeholder="Šifra"
            className={styles.input}
            value={formData.password}
            onChange={handleChange}
            required
          />
          <button type="submit" className={styles.button}>Prijavi se</button>
        </form>
      </div>
    </div>
  );
};

export default Login;

// skill-swap-front/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  standalone: true,
  imports: [FormsModule, CommonModule]
})

export class LoginComponent {
  formData = {
    username: '',
    password: ''
  };

  constructor(private authService: AuthService, private router: Router) {}

  submit() {
    if (!this.formData.username || !this.formData.password) {
      alert('Molimo vas popunite sva obavezna polja.');
      return;
    }

    this.authService.loginRequest(this.formData).subscribe({
      next: (res: any) => {
        localStorage.setItem('token', res.access_token);
        localStorage.setItem('userId', JSON.stringify(res.user));
        this.router.navigate(['/']);
      },
      error: (err) => {
        console.error('Greška pri prijavi', err);
        alert(`Greška: ${err.error?.message || 'Neuspešna prijava'}`);
      }
    });
  }
}

<div class="container">
  <div class="authBox">
    <h1 class="heading">Prijavi se</h1>
    <form (ngSubmit)="submit()" class="form">
      <input
        type="text"
        name="username"
        placeholder="Korisničko ime"
        [(ngModel)]="formData.username"
        class="input"
        required
      />
      <input
        type="password"
        name="password"
        placeholder="Šifra"
        [(ngModel)]="formData.password"
        class="input"
        required
      />
      <button type="submit" class="button">Prijavi se</button>
    </form>
  </div>
</div>
