// skill-swap-front/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { AuthService } from '../../services/auth/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  standalone: true,
  imports: [CommonModule],
})
export class HomeComponent implements OnInit {
  isLoggedIn$!: Observable<boolean>;

  constructor(private authService: AuthService) {}

  ngOnInit(): void {
    this.isLoggedIn$ = this.authService.loggedIn$;
  }
}

<div class="container">
  <ng-container *ngIf="isLoggedIn$ | async; else loggedOut">
    <div class="loggedInContent">
      <h1 class="heading">Dobrodošao/la nazad!</h1>
      <p class="text">Spreman/spremna za razmenu veština?</p>
      <p class="text">Pregedaj ponude za svoje zahteve ili kreiraj novi zahtev.</p>
      <p class="text">Pretraži veštine koje se traže i ponudi razmenu!</p>
      </div>
  </ng-container>

  <ng-template #loggedOut>
    <div class="loggedOutContent">
      <h1 class="heading">Dobrodošli u Skill Swap!</h1>
      <p class="description">
        Platforma za razmenu veština među komšijama.
        Pronađi nekoga sa veštinom koja ti je potrebna i ponudi svoju u zamenu.
      </p>
    </div>
  </ng-template>
</div>

// skill-swap-frontend/src/pages/home/Home.tsx
import { useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import styles from './Home.module.css';

const Home = () => {
  const { isLoggedIn } = useContext(AuthContext);

  return (
    <div className={styles.container}>
      {isLoggedIn ? (
        <div className={styles.loggedInContent}>
          <h1 className={styles.heading}>Dobrodošao/la nazad!</h1>
          <p className={styles.text}>Spreman/spremna za razmenu veština?</p>
          {/* Ovde možeš dodati linkove ili komponente za ulogovane korisnike */}
        </div>
      ) : (
        <div className={styles.loggedOutContent}>
          <h1 className={styles.heading}>Dobrodošli u Skill Swap!</h1>
          <p className={styles.description}>
            Platforma za razmenu veština među komšijama.
            Pronađi nekoga sa veštinom koja ti je potrebna i ponudi svoju u zamenu.
          </p>
        </div>
      )}
    </div>
  );
};

export default Home;
