// skill-swap-frontend/src/pages/profile/Profile.tsx
import { useEffect, useState } from 'react';
import styles from './Profile.module.css';
import type { User } from '../../types/User';
import SkillForm from './SkillFormModal';
import type { Skill } from '../../types/Skill';

const UserProfile = () => {
  const [user, setUser] = useState<User | null>(null);
  const [showSkillForm, setShowSkillForm] = useState<'edit' | 'delete' | 'add' | null>(null);
  const [selectedSkills, setSelectedSkills] = useState<Skill | null>(null);

  const fetchUserData = async () => {
    const token = localStorage.getItem('token');
    const userId = localStorage.getItem('userId');
    if (!token || !userId) {
      console.error('Korisnik nije prijavljen');
      return;
    }

    try {
      const response = await fetch(`http://localhost:3000/auth/profile`, {
        headers: {
        'Authorization': `Bearer ${token}`,
      }
      });
      const data = await response.json();

      if (!response.ok) {
        console.error('Greška pri preuzimanju korisničkih podataka:', data);
        alert('Greška pri učitavanju profila.');
        return;
      } 

      const offersRes = await fetch(`http://localhost:3000/skill-offer?userId=${userId}`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });
      const offersData = await offersRes.json();

      setUser({ ...data, offers: offersData });
    
    } catch (error) {
      console.error('Došlo je do greške pri slanju zahteva:', error);
    }
  };

  useEffect(() => {
    fetchUserData();
  }, []);

  const handleAction = async (action: 'edit' | 'delete' | 'add', skill?: Skill) => {
    setSelectedSkills(skill || null);
    setShowSkillForm(action);
  };

  const handleSave = async (skillData: Skill) => {
    const token = localStorage.getItem('token');
    if(!token) return;

    const url = showSkillForm === 'add' 
      ? `http://localhost:3000/skill-offer` 
      : `http://localhost:3000/skill-offer/${selectedSkills?.id}`;
    const method = showSkillForm === 'add' ? 'POST' : 'PATCH';

    try {
      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(skillData),
      });
      const data = await response.json();

      if (!response.ok) {
        console.error(`Greška pri ažuriranju veština:`, data);
        return null;
      }

      setUser((prevUser) => {
        if (!prevUser) return prevUser;

        if (showSkillForm === 'add') {
          return { ...prevUser, offers: [...(prevUser.offers ?? []), data] };
        } else {
          return {
            ...prevUser,
            offers: prevUser.offers?.map((o) => (o.id === data.id ? data : o)) ?? [],
          };
        }
      });
      setShowSkillForm(null);
    } catch (error) {
      console.error('Došlo je do greške pri slanju zahteva:', error);
      return null;
    }
  };

  const handleDelete = async () => {
    const token = localStorage.getItem('token');
    if (!token || !selectedSkills) return;

    try {
      const response = await fetch(`http://localhost:3000/skill-offer/${selectedSkills.id}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
        },
      });

      if (response.ok) {
        setUser((prevUser) => ({
          ...prevUser!,
          offers: (prevUser?.offers ?? []).filter((offer) => offer.id !== selectedSkills.id),
        }));
        setShowSkillForm(null);
      } else {
        const data = await response.json();
        console.error(`Greška pri brisanju veština:`, data);
      }
    } catch (error) {
      console.error('Došlo je do greške pri slanju zahteva:', error);
    }
  };

  if (!user) {
    return <div className={styles.container}>Učitavanje profila...</div>;
  }

  return (
    <div className={styles.container}>
      <div className={styles.profileHeader}>
        <img src={user.profilePicture} alt="Profilna slika" className={styles.profileImage} />
        <h1 className={styles.username}>{user.username}</h1>
      </div>
      <div className={styles.profileDetails}>
        <div className={styles.detailItem}>
          <span>Ime i prezime:</span>
          <span>{user.firstName} {user.lastName}</span>
        </div>
        <div className={styles.detailItem}>
          <span>Email:</span>
          <span>{user.email}</span>
        </div>
        <div className={styles.detailItem}>
          <span>Broj telefona:</span>
          <span>{user.phoneNumber}</span>
        </div>
      </div>
      <div className={styles.skillsSection}>
        <h2>Veštine</h2>
        <div className={styles.skillsTable}>
          <div className={styles.tableHeader}>
            <div className={styles.column}>Kategorija</div>
            <div className={styles.column}>Opis</div>
            <div className={styles.column}>Status</div>
            <div className={styles.column}></div>
          </div>
          {Array.isArray(user.offers) && user.offers.map(offer => (
            <div key={offer.id} className={styles.tableRow}>
              <div className={styles.column}>{offer.title}</div>
              <div className={styles.column}>{offer.description}</div>
              <div className={styles.column}>{offer.status}</div>
              <div className={styles.column}>
                <button onClick={() => handleAction('edit', offer)}>Izmeni</button>
                <button onClick={() => handleAction('delete', offer)}>Obriši</button>
              </div>
            </div>
          ))}
          <div className={styles.tableRow}>
            <button className={styles.newButton} onClick={() => handleAction('add')}>
              Nova veština
            </button>
          </div>
        </div>
      </div>

      {showSkillForm && (
        <SkillForm
          mode={showSkillForm}
          skill={selectedSkills}
          onClose={() => setShowSkillForm(null)}
          onSave={handleSave}
          onDelete={handleDelete}
        />
      )}
    </div>
  );
};

export default UserProfile;

// skill-swap-front/src/app/pages/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { Skill } from '../../models/skill.model';
import { User } from '../../models/user.model';
import { SkillService } from '../../services/skill-offer/skill-offer.service';
import { AuthService } from '../../services/auth/auth.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { SkillFormComponent } from './skill-form/skill-form.component';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
  standalone: true,
  imports: [FormsModule, CommonModule, SkillFormComponent]
})
export class ProfileComponent implements OnInit {
  user: User | null = null;
  showSkillForm: 'edit' | 'delete' | 'add' | null = null;
  selectedSkill: Skill | null = null;

  constructor(private skillService: SkillService, private authService: AuthService) {}

  ngOnInit(): void {
    this.fetchUserData();
  }

  fetchUserData() {
    const token = localStorage.getItem('token');
    const userId = localStorage.getItem('userId');

    if (!token || !userId) return;

    fetch(`${'http://localhost:3000/auth/profile'}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        this.skillService.getUserSkills(userId, token).subscribe(skills => {
          this.user = { ...data, offers: skills };
        });
      })
      .catch(err => console.error(err));
  }

  openSkillForm(mode: 'edit' | 'delete' | 'add', skill?: Skill) {
    this.selectedSkill = skill || null;
    this.showSkillForm = mode;
  }

  closeSkillForm() {
    this.showSkillForm = null;
    this.selectedSkill = null;
  }

  saveSkill(skill: Skill) {
    const token = localStorage.getItem('token');
    if (!token) return;

    const obs = this.showSkillForm === 'add' 
      ? this.skillService.addSkill(skill, token)
      : this.skillService.editSkill(skill, token);

    obs.subscribe(data => {
      if (!this.user) return;
      if (this.showSkillForm === 'add') {
        this.user.offers = [...(this.user.offers ?? []), data];
      } else {
        this.user.offers = this.user.offers?.map(o => o.id === data.id ? data : o);
      }
      this.closeSkillForm();
    });
  }

  deleteSkill() {
    const token = localStorage.getItem('token');
    if (!token || !this.selectedSkill) return;

    this.skillService.deleteSkill(this.selectedSkill.id!, token).subscribe(() => {
      if (!this.user) return;
      this.user.offers = this.user.offers?.filter(o => o.id !== this.selectedSkill!.id);
      this.closeSkillForm();
    });
  }
}

<div *ngIf="!user">Učitavanje profila...</div>
<div *ngIf="user" class="container">
  <div class="profileHeader">
    <img [src]="user.profilePicture" class="profileImage" />
    <h2>{{ '@' + user.username }}</h2>
  </div>
  
  <div class="profileDetails">
    <div class="detailItem">
      <span>Ime i prezime:</span>
      <span>{{ user.firstName }} {{ user.lastName }}</span>
    </div>
    <div class="detailItem">
      <span>Adresa:</span>
      <span>{{ user.address }}</span>
    </div>
    <div class="detailItem">
      <span>Broj telefona:</span>
      <span>{{ user.phoneNumber }}</span>
    </div>
  </div>

  <div class="skillsSection">
    <h2>Veštine</h2>
    <div class="skillsTable">
      <div class="tableHeader">
        <div class="column">Kategorija</div>
        <div class="column">Opis</div>
        <div class="column">Status</div>
        <div class="column"></div>
      </div>
      <div class="tableRow" *ngFor="let offer of user.offers">
        <div class="column">{{ offer.title }}</div>
        <div class="column">{{ offer.description }}</div>
        <div class="column">{{ offer.status }}</div>
        <div class="column">
          <button (click)="openSkillForm('edit', offer)">Izmeni</button>
          <button (click)="openSkillForm('delete', offer)">Obriši</button>
        </div>
      </div>
      <div class="tableRow">
        <button class="newButton" (click)="openSkillForm('add')">Nova veština</button>
      </div>
    </div>
  </div>

  <app-skill-form 
    *ngIf="showSkillForm" 
    [mode]="showSkillForm" 
    [skill]="selectedSkill" 
    (onSave)="saveSkill($event)" 
    (onDelete)="deleteSkill()" 
    (onClose)="closeSkillForm()">
  </app-skill-form>
</div>
