// skill-swap-front/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
  standalone: true,
  imports: [CommonModule, RouterLink]
})
export class NavbarComponent {
  constructor(public authService: AuthService, private router: Router) {}

  handleLogout() {
    this.authService.logout();
    localStorage.removeItem('token');
    localStorage.removeItem('userId');
    this.router.navigate(['/']);
  }
}

<nav class="navbar">
  <a routerLink="/" class="logo">Skill Swap</a>
  <div class="navLinks">
    <ng-container *ngIf="!authService.isLoggedIn(); else loggedIn">
      <a routerLink="/login" class="navLink">Prijavi se</a>
      <a routerLink="/register" class="navLink">Registruj se</a>
    </ng-container>

    <ng-template #loggedIn>
      <a routerLink="/request-search" class="navLink">Pretraga zahteva</a>
      <a routerLink="/myrequests" class="navLink">Moji zahtevi</a>
      <a routerLink="/profile" class="navLink">Profil</a>
      <button class="logoutButton" (click)="handleLogout()">Odjavi se</button>
    </ng-template>
  </div>
</nav>

// skill-swap-frontend/src/navbar/Navbar.tsx
import { useContext } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import styles from './Navbar.module.css';
import { AuthContext } from '../context/AuthContext';

const Navbar = () => {
  const { isLoggedIn, logout } = useContext(AuthContext);
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    localStorage.removeItem('token');
    localStorage.removeItem('userId');
    navigate('/');
  };

  return (
    <nav className={styles.navbar}>
      <Link to="/" className={styles.logo}>Skill Swap</Link>
      <div className={styles.navLinks}>
        {!isLoggedIn ? (
          <>
            <Link to="/login" className={styles.navLink}>Prijavi se</Link>
            <Link to="/register" className={styles.navLink}>Registruj se</Link>
          </>
        ) : (
          <>
            <Link to="/profile" className={styles.navLink}>Profil</Link>
            <Link to="/requests" className={styles.navLink}>Zahtevi</Link>
            <button onClick={handleLogout} className={styles.logoutButton}>Odjavi se</button>
          </>
        )}
      </div>
    </nav>
  );
};

export default Navbar;
